# This sample deploys the ForgeRock Identity Platform to the `xn--59g` (∞) namespace.
# aka the psuedo "prod" instance that is upgraded instead of being redeployed.
# This sample uses the nightly deployment pipeline,
# except that the persistence tier (`cts` and `idrepo` stores) are not created
# from scratch every night.
#
# If you ever need to recreate the directory services, run teh "nightly" pipeline and s

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: prod
spec:
  params:
  - name: gitrevision
    value: master
  - name: gitrepositoryurl
    value: https://stash.forgerock.org/scm/cloud/forgeops.git

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: prod
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
    default: https://stash.forgerock.org/scm/cloud/forgeops.git
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: prod-run-
    spec:
      timeout: 45m
      serviceAccountName: tekton-worker
      pipelineRef:
        name: nightly-pipeline
      params:
      - name: "notify"
        value: "false"
      - name: "namespace"
        value: "xn--59g"
      # This does not work right now https://github.com/tektoncd/pipeline/pull/3176
      # - name: "nuke"
      #   value: "false"
      resources:
      - name: forgeops
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: prod-listener
spec:
  serviceAccountName: tekton-trigger
  triggers:
    - name: cron-trig
      bindings:
      - ref: prod
      template:
        ref: prod

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prod-cronjob
spec:
  schedule: "10 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: curlimages/curl
            args: ["curl", "-X", "POST" , "--data" ,"{}", "el-prod-listener:8080" ]
          restartPolicy: Never
