# Skaffold used for testing the ds image. You need to deploy the forgeops-secrets first for ds to come up
# Run using  skaffold dev --port-forward
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ds
build:
  artifacts:
  - image: ds-idrepo
    context: .
    docker:
      dockerfile: idrepo/Dockerfile
  - image:  ds-cts
    context: .
    docker:
      dockerfile: cts/Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
profiles:
- name: ds-operator
  deploy:
    kustomize:
      paths:
      - ../../../kustomize/base/ds-idrepo
      - ../../../kustomize/base/ds-cts
      - ../../../kustomize/base/secrets



