kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 namespace: prod
 name: rep-ds-idrepo-0-eu
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 namespace: prod
 name: rep-ds-cts-0-eu
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 namespace: prod
 name: rep-ds-idrepo-1-eu
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 namespace: prod
 name: rep-ds-cts-1-eu