# This enables kustomize to replace variables in ConfigMap (data is the path spec for replacement)
images:
- path: spec/image
  kind: DirectoryService
replicas:
- path: spec/replicas
  kind: DirectoryService