apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-images
spec:
  resources:
    inputs:
    - name: forgeops
      type: git
  params:
  - name: profile
    type: string
    description: profile to deploy

  - name: namespace
    type: string
    description: target namespace

  - name: docker-repo
    type: string
    description: Docker repository URL
  - name: gitrevision
    type: string
    description: tag name environment variable used in some skaffold profiles
  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: "slack-webhook-utils"
          key: SLACK_FAILED_WEBHOOK_URL
  steps:
  - name: build-images
    env:
      - name: GIT_TAG_NAME
        value: $(params.gitrevision)
    image: "gcr.io/engineering-devops/skaffold:latest"
    script: |
      #!/usr/bin/env bash
      # if there's a tag name change master to latest
      set -x
      export IMAGE_TAG=${GIT_TAG_NAME/master/latest}
      {
        cd /workspace/forgeops
        # TODO remove these steps, and just use the command key when tekton will checkout a tag
        git fetch --tags
        git checkout "${GIT_TAG_NAME}"
       ./bin/config.sh init -p cdk
        skaffold -f skaffold.yaml -p $(params.profile) --default-repo=$(params.docker-repo) build
      } || {
      #curl -X POST -H 'Content-type: application/json' --data '{"text":"Skaffold failed to build \`$(params.profile)\`. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
        exit 1
      }
