apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nuke-deployment
spec:
  params:
  - name: namespace
    type: string
    description: target namespace
  steps:
  # Nuke everything in the namespace
  - name: delete-deployment
    image: "gcr.io/engineering-devops/skaffold:latest"
    script: |
      #!/usr/bin/env bash
      set -x
      kubectl -n '$(params.namespace)' delete sts,service,deployment,job,cronjob,ingress --all
      kubectl -n '$(params.namespace)' delete  directoryservice --all
      # Wait for the directory to delete before deleting secrets. Just in case the
      # ds-operator is performing a reconcile.
      sleep 5
      kubectl -n '$(params.namespace)' delete  secretagentconfiguration --all

      kubectl  -n '$(params.namespace)' delete pvc --all
