# Deploys the apps only
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skaffold-deploy-apps
spec:
  resources:
    inputs:
    - name: forgeops
      type: git
  results:
  - name: status
    description: Deployment status

  params:
  - name: namespace
    type: string
    description: namespace to deploy in.

  - name: skaffold-file
    type: string
    description: Filename of skaffold.yaml
    default: nightly.yaml

  - name: docker-repo
    type: string
    default: gcr.io/engineering-devops/nightly

  steps:
  - name: deploy-new-env
    image: "gcr.io/engineering-devops/skaffold:latest"
    script: |
      #!/usr/bin/env bash
      cd /workspace/forgeops
      {
        set -e -o pipefail
        set -x
        # First delete any existing apps. Should not be required... but safer
        skaffold -n '$(params.namespace)' -f '$(params.skaffold-file)'  -p amster --default-repo='$(params.docker-repo)' delete
        skaffold -n '$(params.namespace)' -f '$(params.skaffold-file)'  -p apps --default-repo='$(params.docker-repo)' delete
        # Get the fresh config
        ./bin/config.sh init -v 7.0 -p cdk
        # Deploy the apps
        skaffold -n '$(params.namespace)'  -f '$(params.skaffold-file)'  -p apps --default-repo='$(params.docker-repo)' run
        # TODO: What is the best way to wait for the apps to be available?
        # The dynamic clients are not refreshed by default. Uncomment if you want rerun amster:
        # skaffold -n '$(params.namespace)'  -f '$(params.skaffold-file)'  -p amster --default-repo='$(params.docker-repo)' run
      } || {
        msg="Skaffold failed to deploy the prod apps environment. See pipeline logs"
        echo $msg | tee /tekton/results/status
        exit 1
      }