# Runs the smoke test as a service
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: smoke-test
spec:
  resources:
    inputs:
    - name: forgeops
      type: git
  params:
  - name: namespace
    type: string
    description: target namespace
  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: "slack-webhook-smoke"
          key: SLACK_FAILED_WEBHOOK_URL
    - name: NAMESPACE
      value: $(params.namespace)
  volumes:
  - name: scripts
    configMap:
      name: tekton-scripts
      defaultMode: 0755
  steps:
  # Run the smoke test by POSTing to the smoke cloud run service
  - name: run-smoke
    image: "gcr.io/engineering-devops/skaffold:latest"
    volumeMounts:
    - name: scripts
      mountPath: /mnt/scripts
    command: [ "/mnt/scripts/run-smoke-test.sh"]