# The smoke test triggger runs the `nightly` pipeline anytime a commit is made to the `forgeops` stash repo.
# Unlike the `nightly` pipeline, this is deployed to the `smoke` namespace, and
# slack notifications are not generated.

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: smoke
spec:
  params:
  # This expression does not appear to exist in the stash payload. Suspect it is defaulting to "", which
  # is subsquently getting set to the param.default value of "master"
  # - name: gitrevision
  #   value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: "https://stash.forgerock.org/scm/cloud/forgeops.git"
  # From the tekton bitbucket sample.
  - name: gitrevision
    value: $(body.changes[0].ref.displayId)
  # - name: gitrepositoryurl
  #   value: $(body.repository.links.clone[0].href)
  # See https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html for on prem stash sample
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: smoke
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: smoke-run-
    spec:
      timeout: 30m
      serviceAccountName: tekton-worker
      pipelineRef:
        name: nightly-pipeline
      params:
      - name: "notify"
        value: "false"
      - name: "namespace"
        value: "smoke"
      resources:
      - name: forgeops
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: smoke-listener
spec:
  serviceAccountName: tekton-trigger
  triggers:
  - name: stash-trigger
    interceptors:
    - bitbucket:
        secretRef:
          secretName: git-webhook-secret
          secretKey: secret
        eventTypes:
        # todo: What are the allowable event types?
        # See https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/ for hosted bitbucket
        # https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html - for stash
        # Note they are not exactly the same!
        # Other event types in stash:
        # pr:opened
        # pr:from_ref_updated - source branch updated
        # pr:modified -
        - repo:refs_changed
    bindings:
    - ref: smoke
    template:
      ref: smoke
