timeout: 900s
options:
  env:
    - NAMESPACE=smoke
    - DOCKER_REPO=gcr.io/engineering-devops

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: authenticate
  waitFor: ['-']
  args: ['container', 'clusters', 'get-credentials', 'eng-experimental', '--region=us-east1']

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: build-images
  waitFor: ['authenticate']
  env:
    - DEFAULT_DOCKER_REPO=gcr.io/engineering-devops
  args:
    - -c
    - |-
      ./bin/config.sh add
      ./bin/cdk build am amster idm ds-idrepo --default-repo $$DEFAULT_DOCKER_REPO
  
- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: nuke-environment
  waitFor: ['build-images']
  args:
    - -c
    - |-
      ./bin/cdk delete -n $$NAMESPACE --yes

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: deploy-cdk
  waitFor: ['nuke-environment']
  args:
    - -c
    - |-
      ./bin/cdk install --fqdn smoke.iam.forgeops.com -n $$NAMESPACE

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: smoke-tests
  waitFor: ['deploy-cdk']
  args:
    - -c
    - |-
      ./cicd/bin/smoke-tests
