apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  serviceAccountName: toolbox
  containers:
  - name: toolbox
    image: gcr.io/forgeops-public/toolbox:latest
    imagePullPolicy: Always
    args: ["pause"]
    ports:
    - containerPort: 4222
    volumeMounts:
    - name: workspace
      mountPath: "/opt/workspace"
    resources: {}  # for now ignore resource limits
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: storage-claim


