kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/name: rcs-agent
  app.kubernetes.io/instance: rcs-agent
  app.kubernetes.io/component: rcs-agent
  app.kubernetes.io/part-of: forgerock
  tier: middle
  app: rcs-agent
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
